<?php

namespace R9\InbizzBundle\Repository;

/**
 * ContactprojetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactprojetRepository extends \Doctrine\ORM\EntityRepository
{
}
