#Custom Routes
r9_core:
    resource: "@R9CoreBundle/Resources/config/routing.yml"
    prefix:   /

r9_inbizz:
    resource: "@R9InbizzBundle/Resources/config/routing.yml"
    prefix:   /

#FosUserBundle Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

# facebook_login:
#     path: /login/check-facebook

google_login:
    path: /login/check-google

# custom_login:
#     path: /login/check-custom

# github_login:
#     path: /login/check-github
