# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  encoders:
    # Symfony\Component\Security\Core\User\User: plaintext
    R9\UserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email
      # id: fos_user.user_provider.username
    oauth:
      id: r9.oauth.user_provider

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      form_login:
        provider: fos_userbundle
#        csrf_provider: form.csrf_provider
        login_path: /login
        check_path: /login_check
      oauth:
        resource_owners:
        #  github:             "/login/check-github"
          google:             "/login/check-google"
        #  facebook:           "/login/check-facebook"
        #  my_custom_provider: "/login/check-custom"
        login_path:        /login
        failure_path:      /login

        # FOSUB integration
        oauth_user_provider:
        #  service: hwi_oauth.user.provider.fosub_bridge
          service: r9.oauth.user_provider
      
      logout:
        path:           /logout
        target:         / #where to go after logout

      anonymous: true

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/adduser, role: ROLE_ADMIN }
    - { path: ^/register, role: ROLE_ADMIN }
    - { path: ^/profile, role: ROLE_ADMIN }
    - { path: ^/resetting, role: ROLE_ADMIN }
    - { path: ^/admin/, role: ROLE_ADMIN }